-- MySQL Script generated by MySQL Workbench
-- Wed Apr 11 20:32:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fallback
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fallback
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fallback` DEFAULT CHARACTER SET utf8 ;
USE `fallback` ;

-- -----------------------------------------------------
-- Table `fallback`.`STRING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fallback`.`STRING` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fqdn` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fqdn_UNIQUE` (`fqdn` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fallback`.`LOCALE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fallback`.`LOCALE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `locale` VARCHAR(5) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `locale_UNIQUE` (`locale` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fallback`.`LOCALIZED_STRING`
-- -----------------------------------------------------
drop TABLE LOCALIZED_STRING;
CREATE TABLE IF NOT EXISTS `fallback`.`LOCALIZED_STRING` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `string_id` INT NOT NULL,
  `locale_id` INT NOT NULL,
  `1i18n_string` VARCHAR(200) NOT NULL ,
  PRIMARY KEY (`id`, `string_id`, `locale_id`),
  INDEX `fk_LocalizedString_String_idx` (`string_id` ASC),
  INDEX `fk_LocalizedString_locale1_idx` (`locale_id` ASC),
  CONSTRAINT `fk_LocalizedString_String`
  FOREIGN KEY (`string_id`)
  REFERENCES `fallback`.`STRING` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LocalizedString_locale1`
  FOREIGN KEY (`locale_id`)
  REFERENCES `fallback`.`LOCALE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO LOCALE(locale) VALUES ('en'), ('en-US'), ('ko-KR'), ('ko');
INSERT INTO STRING(fqdn) VALUES ('store.hello');
SET @sid = LAST_INSERT_ID();
select * from STRING;
SELECT * FROM LOCALE;
DELETE FROM LOCALIZED_STRING;
INSERT INTO LOCALIZED_STRING(string_id, locale_id, `1i18n_string`) VALUES (1, 1, 'hello-en'), (1,2,'hello en-US'), (1,3,'안녕하세요 ko-KR'), (1,4, 'hello ko');
SELECT * from LOCALIZED_STRING;

SELECT 1 as seq, LS.`1i18n_string` FROM STRING S
  INNER JOIN LOCALIZED_STRING LS ON S.id=LS.string_id
INNER JOIN LOCALE L ON LS.locale_id = L.id
WHERE L.locale='en-US' AND S.fqdn='store.hello'
UNION
SELECT 2 as seq, LS.`1i18n_string` FROM STRING S
  INNER JOIN LOCALIZED_STRING LS ON S.id=LS.string_id
  INNER JOIN LOCALE L ON LS.locale_id = L.id
WHERE L.locale='en' AND S.fqdn='store.hello'
ORDER BY seq ASC LIMIT 1;



select * from LOCALIZED_STRING;
